import './globals.css';
import ToastProvider from '@/components/ToastProvider';
import Navbar from '@/components/shared/Navbar';
import QueryProvider from '@/providers/QueryProvider';

export const metadata = {
  title: 'SwiftCart',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <ToastProvider />
        <header>
          <Navbar />
        </header>
        <main>
          <QueryProvider>{children}</QueryProvider>
        </main>
      </body>
    </html>
  );
}
